# Generated by Django 6.1.1 on 2026-10-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('multiple_choice', 'Múltipla escolha'), ('true_false', 'Verdadeiro ou falso'), ('short_answer', 'Resposta curta')], max_length=30)),
                ('dados', models.JSONField(default=dict)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('vestibular', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='content.assunto')),
            ],
        ),
    ]
