# Generated by Django 6.1.1 on 2026-10-06 23:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_rename_descricao_assunto_conteudo_and_more'),
        ('exercises', '0002_alter_questao_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('porcentagem_acerto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aprovada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='content.assunto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resposta', models.JSONField()),
                ('acertou', models.BooleanField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='learning.prova')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='exercises.questao')),
            ],
        ),
    ]
