# Generated by Django 6.1.1 on 2026-10-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_questao_id'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='questoes',
            field=models.ManyToManyField(related_name='provas', to='exercises.questao'),
        ),
    ]
