# Generated by Django 6.1.1 on 2026-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_assunto_id_alter_materia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assunto',
            old_name='descricao',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='assunto',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
